[build]
builder = "nixpacks"
buildCommand = "npm run build:web"
watchPatterns = ["web/**"]

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"

[healthcheck]
path = "/health"
intervalSeconds = 30
timeoutSeconds = 10